import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import SingleNews from '../components/SingleNews'
import Banner from '../components/Banner'
import { useEffect, useState } from 'react'
import Footer from '../components/Footer'



export default function Home() {
  let [news, setNews] = useState([])
  useEffect(()=>{
    fetch('/news.json')
    .then(res => res.json())
    .then(data => setNews(data.slice(0,4)))
  },[])

  return (
    <>
      <Head>
        <title>News Caster</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''>

        {/* banner div  */}
        <Banner />

        {/* purple div  */}
        <div className='max-w-6xl mx-auto bg-[#E0CECE] text-[#632727] flex gap-14 text-3xl justify-center p-5'>
          <h1 className='italic underline'>Sports</h1>
          <h1>Bangladesh wins series with India!
          </h1>
        </div>

        {/* cards  */}
        <div className='my-10 max-w-6xl mx-auto grid grid-cols-3 gap-16'>
          <div className='col-span-2'>
            <h1 className='text-xl font-bold p-5 bg-white mb-5'><span className='border-b-2 border-[#C31815] pb-1'>Late</span>st Stories</h1>
            <div className='grid grid-cols-2 gap-5'>
              {
                news?.map(n => <SingleNews
                key={n?.id}
                n={n}
                ></SingleNews>)
              }
            </div>
          </div>
          <div>
            adadadad
          </div>
        </div>

        <Footer/>
      </main>
    </>
  )
}
